
public class EmptySetException extends Exception {
	
	/**
	 * serialVersionUID generated by Eclipse
	 */
	private static final long serialVersionUID = -9162791177362385299L;

	public EmptySetException(String message) {
        super(message); 
    }
}
